### ISSUE TITLE
Can compile but app closes immediately

### ISSUE THREAD

**Issue by hvdwolf** [lbdroid/dashcam_frontend#4]
Hi,

I wanted to stop the log.d commands and wanted to switch to standard gps-time, lat, lon, speed, accurracy instead of nmea, as the log.d makes the logcat grow extremely fast and the full nmea log makes the database grow very fast. And gpx lat, lon is also much easier to read and handle in other programs.
Anyway, I patched it and compiled it. The app starts and immediately gives an an error and stops.
However, as such that is not the point as it could be my very clumsy attemps. Even though I can't imagine that simply remarking out the log.d lines would break the code (using (`//`  or `/* log.d(......  */`).

So I cloned again an original repo and simply built it. That one also crashes on startup.
Some things I should take into account when building the dashcam apk?

Note that when cloning the repo I also get an error message. I have to 'cd' into the repo folder and have to do a `git checkout picamd`, otherwise I have an "empty" folder.
Downloading the zip and compiling that one, doesn't give me a working app either.

**Comment by hvdwolf** [comment]
It is weird. 
Yesterday evening I tried many things, and this morning again (testing on my phone by the way)
All versions crash on startup.
Tired of it I put my phone aside, and suddenly after 10 minutes or so I noticed the camera icon in the bar. It turned out to run.
Then I compiled my patch again and installed it . (Of course) It crashed again upon starting up, but this time I put my phone aside and after a couple of minutes (5? 10? I did not check), my version ran as well.
And it wrote the gps-time, lat, lon, speed, accurracy in csv format as string to the value field.

I don't get this at all. Maybe you do.

**Comment by lbdroid** [comment]
Can't help without a log.
Current head has been running on my car without issue for the last 2 weeks.

There are two problems with what you are doing;
1) if you modify the NMEA, it is no longer admissible, and since the purpose is exclusively for collection of evidence, that makes it pointless.
2) the growth of the database is bounded. See https://github.com/lbdroid/dashcam_frontend/blob/picamd/app/src/main/java/tk/rabidbeaver/dashcam/DashCamService.java#L206
** so there is really no reason to worry about its size.

**Comment by hvdwolf** [comment]
On my phone I can't get "deep" access to my logcat. Only some superficial phone info is displayed/downloaded (-d) via terminal. I can't get adb to work either without rooting it somehow. As it is a company phone, I'm not allowed to do that.
When I copied it on my head unit I did not get any error at all, so no log either. I ran it for about an hour without any error. Must be something with my phone (Lenovo Motorola 5G Plus; Android 7.0).

1. Where can I find the info about nmea being mandatory? I can't find it in English and neither in Dutch for my country.

2. Yes, I did see that later. About 5 minutes before I read your reply.

Maybe I should indeed leave it to what it is, but I can see immediately what is what in my GPS approach.

**Comment by lbdroid** [comment]
The problem with just taking down coordinates and time, is that its much easier to fake than the raw NMEA, which can be corroborated (there are much more details in the NMEA stream, including details of the actual satellites that were being used). So if you go into court to fight a cop saying that you ran over someone but you were a hundred miles away at the time, they are much more likely to believe the NMEA than something you could have written down any time after the prosecution made their disclosure.

And besides which, the coordinates and time are plainly written in the NMEA stream anyway. Parsing them out in a way that is easier for you to visualize is less than trivial.


About those logs though, there is really no way to figure out the problem without being able to either reproduce the problem, or at the very least, see the backtrace from the crash, which will tell us what the origin point of the crash is.

From a terminal running on the phone, you are right that there will be no way to get a full logcat. All it will show is the details that are applicable to *THAT* process. So what you might have to do is look into an uncaughtexceptionhandler. https://stackoverflow.com/questions/8943288/how-to-implement-uncaughtexception-android

**Comment by hvdwolf** [comment]
I suggest to close this.
My self compiled version fails on startup but only on my phone, and after a few minutes it turns out to be running and functioning fine as well. My version also works fine on the unit.
Your version never failed. Not on my phone and neither on my unit where it had run fine for weeks.
I have already re-installed your version.
A simple query from the db to (nmea) file and import into (for example) routeconverter, gives me everything I need.

(After having programmed in basic, pascal, C, SQL, applescript, javascript, php, shell, labview, appinventor and python I wanted to try some java, but not too much)
